"""
Codex Client - OpenAI Codex API Wrapper
SAI ROLO TECH
"""

import os
from typing import Dict, List, Optional


class CodexClient:
    """Wrapper for OpenAI Codex API calls."""

    def __init__(self, api_key: str = None, model: str = "gpt-4o"):
        self.api_key = api_key or os.environ.get("OPENAI_API_KEY")
        self.model = model
        self.base_url = "https://api.openai.com/v1"

    def generate(self, plan: str, context: str, feedback: List[Dict] = None) -> Dict:
        """
        Codex generates code based on the plan from ChatGPT.
        Optionally includes feedback from previous verification.
        """
        prompt = self._build_prompt(plan, context, feedback)

        # Simulated code generation for demo
        # In production, this would call the actual Codex API
        code = self._generate_demo_code(context, feedback)

        return {
            "code": code,
            "files": ["generated_code.py"],
            "language": "python",
            "prompt_used": prompt
        }

    def _build_prompt(self, plan: str, context: str, feedback: List[Dict] = None) -> str:
        """Build the prompt for Codex."""
        prompt = f"""Based on the following plan, generate clean, production-ready code:

CONTEXT:
{context}

PLAN:
{plan}
"""

        if feedback:
            prompt += "\n\nPREVIOUS ISSUES TO ADDRESS:\n"
            for i, issue in enumerate(feedback, 1):
                prompt += f"{i}. [{issue.get('severity', 'MEDIUM')}] {issue.get('message', '')} - Fix: {issue.get('suggestion', '')}\n"

        prompt += "\n\nGenerate the complete implementation code."

        return prompt

    def _generate_demo_code(self, context: str, feedback: List[Dict] = None) -> str:
        """Generate demo code based on context."""
        # Extract keywords from context
        context_lower = context.lower()

        if "calculator" in context_lower:
            code = '''"""
Calculator Module - Generated by Codex
SAI ROLO TECH
"""

from typing import Union


class Calculator:
    """Simple calculator with basic operations."""

    def __init__(self):
        self.history = []

    def add(self, a: Union[int, float], b: Union[int, float]) -> Union[int, float]:
        """Add two numbers."""
        result = a + b
        self.history.append(f"add({a}, {b}) = {result}")
        return result

    def subtract(self, a: Union[int, float], b: Union[int, float]) -> Union[int, float]:
        """Subtract b from a."""
        result = a - b
        self.history.append(f"subtract({a}, {b}) = {result}")
        return result

    def multiply(self, a: Union[int, float], b: Union[int, float]) -> Union[int, float]:
        """Multiply two numbers."""
        result = a * b
        self.history.append(f"multiply({a}, {b}) = {result}")
        return result

    def divide(self, a: Union[int, float], b: Union[int, float]) -> Union[int, float]:
        """Divide a by b."""
        if b == 0:
            raise ValueError("Cannot divide by zero")
        result = a / b
        self.history.append(f"divide({a}, {b}) = {result}")
        return result

    def power(self, a: Union[int, float], b: Union[int, float]) -> Union[int, float]:
        """Calculate a raised to power b."""
        result = a ** b
        self.history.append(f"power({a}, {b}) = {result}")
        return result

    def get_history(self) -> list:
        """Get calculation history."""
        return self.history.copy()

    def clear_history(self):
        """Clear calculation history."""
        self.history = []


# Demo usage
if __name__ == "__main__":
    calc = Calculator()
    print(f"2 + 3 = {calc.add(2, 3)}")
    print(f"10 - 4 = {calc.subtract(10, 4)}")
    print(f"5 * 6 = {calc.multiply(5, 6)}")
    print(f"20 / 4 = {calc.divide(20, 4)}")
    print(f"2 ** 8 = {calc.power(2, 8)}")
    print(f"History: {calc.get_history()}")
'''
        elif "api" in context_lower or "rest" in context_lower:
            code = '''"""
REST API Module - Generated by Codex
SAI ROLO TECH
"""

from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel
from typing import Optional, List
from datetime import datetime


app = FastAPI(title="SAI Rolotech API", version="1.0.0")


class Item(BaseModel):
    """Item model for API requests."""
    id: Optional[int] = None
    name: str
    description: Optional[str] = None
    price: float
    quantity: int = 0


# In-memory storage
items_db: List[Item] = []
item_id_counter = 1


@app.get("/")
async def root():
    """Root endpoint."""
    return {"message": "SAI Rolotech API", "version": "1.0.0", "status": "running"}


@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {"status": "healthy", "timestamp": datetime.now().isoformat()}


@app.get("/items", response_model=List[Item])
async def list_items(skip: int = 0, limit: int = 100):
    """List all items with pagination."""
    return items_db[skip:skip + limit]


@app.get("/items/{item_id}", response_model=Item)
async def get_item(item_id: int):
    """Get a specific item by ID."""
    for item in items_db:
        if item.id == item_id:
            return item
    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail=f"Item {item_id} not found"
    )


@app.post("/items", response_model=Item, status_code=status.HTTP_201_CREATED)
async def create_item(item: Item):
    """Create a new item."""
    global item_id_counter
    new_item = Item(
        id=item_id_counter,
        name=item.name,
        description=item.description,
        price=item.price,
        quantity=item.quantity
    )
    item_id_counter += 1
    items_db.append(new_item)
    return new_item


@app.put("/items/{item_id}", response_model=Item)
async def update_item(item_id: int, updated_item: Item):
    """Update an existing item."""
    for i, item in enumerate(items_db):
        if item.id == item_id:
            items_db[i] = Item(
                id=item_id,
                name=updated_item.name,
                description=updated_item.description,
                price=updated_item.price,
                quantity=updated_item.quantity
            )
            return items_db[i]
    raise HTTPException(
        status_code=status.HTTP_404_NOT_FOUND,
        detail=f"Item {item_id} not found"
    )


@app.delete("/items/{item_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_item(item_id: int):
    """Delete an item."""
    global items_db
    original_length = len(items_db)
    items_db = [item for item in items_db if item.id != item_id]
    if len(items_db) == original_length:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Item {item_id} not found"
        )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''
        else:
            code = f'''"""
Generated Code - Codex Output
SAI ROLO TECH
Context: {context}
"""

# Implementation based on: {context}

class GeneratedModule:
    """Auto-generated module."""

    def __init__(self):
        self.data = None
        self.initialized = True

    def process(self, input_data):
        """Process input data."""
        # TODO: Add specific processing logic
        self.data = input_data
        return {"status": "processed", "data": self.data}

    def validate(self) -> bool:
        """Validate internal state."""
        return self.data is not None

    def export(self) -> dict:
        """Export current state."""
        return {{
            "data": self.data,
            "valid": self.validate()
        }}
'''

        # If there was feedback, add a comment about it
        if feedback:
            code = f'# Feedback issues addressed:\\n# ' + '\\n# '.join([
            #     f"{i}. {issue.get('suggestion', 'Fixed')}"
            #     for i, issue in enumerate(feedback, 1)
            # ]) + '\\n\\n' + code

        return code
